AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: some description

Resources:
  ## Sync Hello world lambda
  RequestResponseHelloWorldLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      FunctionName: RequestResponseHelloWorldLambda
      MemorySize: 512
      ## This path to lambda to invoke
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      CodeUri: target/learning-aws-lambdas-springboot-1.0.1.jar
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION>: "HelloWorldSpringComponent"