name: Generic build maven with test coverage and sonar and codeql
description: 'Generic build maven with test coverage and sonar and codeql'

inputs:
  sonar_token:
    description: 'Sonar token'
    required: true
  github_token:
    description: 'github token'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'corretto'
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: java
    - name: Build
      run: mvn -B install --file pom.xml
      shell: bash
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_USERNAME: x-access-token
        SONAR_TOKEN: ${{ inputs.sonar_token }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Pcoverage -Dsonar.projectKey=antonovdmitriy_learning-aws-lambda-springboot
      shell: bash